### PR TITLE
Add contributors command

### PR DESCRIPTION
**Pull request by ghost**
This little change makes me smile (●'◡'●)
Added the following:
- Contributors command

- [x] Not tested, couldn't test it because webhooks is giving me some issues.

### CODE REVIEW

**Comment by LucasCtrl** [comment]
I will test it tomorrow 😉

**Comment by ghost** [comment]
Thank you!

**Review by marc2332 — COMMENTED** [review]
Unauthenticated requests to the GitHub API is limited to 60 requests/ip/ 1 hour. Shouldn't be a problem right now, but it might be in the future.

**Comment by LucasCtrl** [comment]
I join @marc2332 about the API limitation even if it's not a very big problem.
But I don't think this feature is really important. We already have a GitHub link in the `help` command and the contributors are in the README.
Especially since I don't think people are very interested in who made the bot. Or at least, if they're really interested, they're doing some research.

**Pull request closed without merging**
