### PR TITLE
Add typescript

### PR DESCRIPTION
**Pull request by ghost**
I have added the following:
- added the typescript dependency
- added spooky.d.ts file

If you want to learn more about typescript and why it is important to have it [go here.](http://typescriptlang.com)

### CODE REVIEW

**Comment by illusi0nary** [comment]
@dragonDScript  what is the current benefit of adding just blank TS to the repo? :see_no_evil:

**Comment by ghost** [comment]
In this pr I have just added the dependency and the file. I'll add more types soon! 👻

**Comment by ghost** [comment]
I didn't have time to add anything more

**Comment by illusi0nary** [comment]
Then i think we should wait till you have time and then we are going for the TS migration! =D

**Comment by illusi0nary** [comment]
Closed for now, since only implementing TS does not create benefits yet.

**Pull request closed without merging**
